### ISSUE TITLE
Remove or contain impact of InternalsVisibleTo

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#197]
Currently, Gax has internals visible to Gax.Rest and Gax.Grpc, as well as to test projects.

This potentially creates a versioning issue, as it's possible that Gax.Rest/Gax.Grpc will be running against a version of Gax that's later than they expect.

For example, suppose library X depends on Gax.Rest v2.1 and library Y depends on Gax.Grpc v2.2. Then an application depending on them both will end up with:

- Gax.Rest v2.1
- Gax.Grpc v2.2
- Gax v2.2

If we don't understand our internal dependencies, that could lead to issues.

We should:

- Check *why* we have InternalsVisibleTo between prod assemblies
- Limit where we use that (ideally with an attribute at each place that's used, and validated with a Roslyn analyzer)
- Be extra careful when making changes

While any breakages *could* be fixed by encouraging users to update all libraries to the same version (e.g. updating Gax.Rest to 2.2 in the example above) it would be better not to have to.

**Comment by jskeet** [comment]
@evildour: How feasible does this sound as a Roslyn analyzer?

"If member invocation X invokes Y in a different assembly, and Y is internal, then Y must be decorated with a particular attribute"?

**Comment by evildour** [comment]
I believe that kind of analyzer would only work if both project X and Y were part of the same solution. I'm not sure what kind of performance issues you'd have though with basically doing a "Find all references" operation on every internal member. Would you want to to cause an error if you had the attribute on something where it wasn't needed?

**Comment by jskeet** [comment]
Hmm. So you can't find the target ISymbol and then the attributes on the symbol, even if they're only in metadata? (It's fine for it only to work on the solution containing X.) But we're going to try to make this a non-issue, I think...

**Comment by evildour** [comment]
Oh I see, so you want the diagnostics to be reported at the call site, not where the symbol is defined? Yes, that should be possible (and would probably be more performant). You'd just receive multiple diagnostics for the same issue if you've referenced the same symbol multiple times, but I don't think that's a problem. So is this something you'd like implemented, or just a hypothetical?

**Comment by jskeet** [comment]
If we find we really, really want internal visibility between libraries, I think we'll want it - but I've managed to remove them from GAX and I'm looking at Spanner now.

**Comment by evildour** [comment]
Ok, let me know. Seems like an easy one to implement.
