### ISSUE TITLE
Monitored resource type incorrect for GKE containers

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#209]
Looking at [the documentation](https://cloud.google.com/logging/docs/api/v2/resource-list) we should be logging with a resource type of "container" rather than "gke_cluster" if we detect we're running in Container Engine.

[This](https://github.com/googleapis/gax-dotnet/blob/master/src/Google.Api.Gax.Grpc/MonitoredResourceBuilder.cs) code should be fixed - but we should check all the other resource types at the same time.

cc @iantalarico

**Comment by chrisdunelm** [comment]
Looks like we're doing the right thing for GCE and GAE (gce_instance and gae_app). Only GKE requires changing.

**Comment by sebbov** [comment]
Do you have an ETA for this?  Depending on the timeline, I might invest on working around it implementing my own MonitoredResource population for the GKE case.  Having all pods in a cluster end up with the same is going to be trouble esp. for custom metrics.  Thanks!

**Comment by sebbov** [comment]
Actually it doesn't seem like using gke_cluster as a monitored resource for metrics works at all with Google.Cloud.Monitoring.V3:
  `Failed to create 3 timeseries status Status(StatusCode=InvalidArgument, Detail="Field timeSeries[0].resource.type had an invalid value of "gke_cluster": Unrecognized resource name."), dropping these. (12/12)`
So I will need to work-around anyhow.  If the above doesn't seem expected, I can dive a bit deeper in it to ensure I'm not doing anything wrong, and file a report for that.  (I personally have no need to report on that cluster resource type).

**Comment by chrisdunelm** [comment]
@sebbov I expect to have this work done by the end of next week, 2017-10-20.

**Comment by sebbov** [comment]
👍 thanks!
