### ISSUE TITLE
Can't get the current Project ID when running on my dev machine.

### ISSUE THREAD

**Issue by ivannaranjo** [googleapis/gax-dotnet#224]
https://github.com/googleapis/gax-dotnet/blob/3488c5b95f383e314d4a22390b599f07aa3057dc/src/Google.Api.Gax/Platform.cs#L543

While I can get the Project ID when running on GAE, GCE or GKE I cannot use the same code to get the Project ID when running locally. That is what the `GOOGLE_CLOUD_PROJECT` environment variable is supposed to do for me.

We should have a 4th type of platform details that allow the code to run unchanged when running on the developer machine with only the `GOOGLE_CLOUD_PROJECT` environment variable set.

**Comment by chrisdunelm** [comment]
Yes, this sounds like a good idea. Is the ProjectId the only useful information that can be learnt from a "local" platform?

**Comment by jskeet** [comment]
Closing as we wouldn't want to do this unilaterally. (There's a lot of work on environment variables that's needed for consistency.)
