### ISSUE TITLE
monitored resource type "container" or "gke_container"?

### ISSUE THREAD

**Issue by sebbov** [googleapis/gax-dotnet#233]
Hello,

I tried to switch to using  `MonitoredResourceBuilder.FromPlatform()` now that [it's supposed to work for GKE]( https://github.com/googleapis/gax-dotnet/issues/209) but I'm getting this error:

```
....Monitoring.Stackdriver.Publisher Failed to create 1 timeseries status
Status(StatusCode=InvalidArgument, Detail="Field timeSeries[0].resource.type had an invalid value of 
"container": Unrecognized resource name."), dropping these. (108/108)
```
Should [`container` here](https://github.com/googleapis/gax-dotnet/blob/master/src/Google.Api.Gax.Grpc/MonitoredResourceBuilder.cs#L89) perhaps be `gke_container`?

As an experiment, I used:

```
var monitoredResource = MonitoredResourceBuilder.FromPlatform();
monitoredResource.Type = "gke_container";
```

But then I get another error!

```
Kaggle.Monitoring.Stackdriver.Publisher Failed to create 1 timeseries status
Status(StatusCode=InvalidArgument, Detail="One or more TimeSeries could not be written: Unrecognized 
region or location.: timeSeries[0]")
```

Looking at the labels, the value for `zone` does look wrong (`projects/.../zones/us-...-d`), over what we used before (simply `us-...-d`):

https://cloud.google.com/monitoring/api/resources#tag_gke_container isn't too useful in determining what this exactly should be, but I'd bet on the short name.

=>

```
var monitoredResource = MonitoredResourceBuilder.FromPlatform();
monitoredResource.Type = "gke_container";
monitoredResource.Labels["zone"] = "us-...-d";
```

which works (can write time series and labels look ok to me).

My code looks a bit closer to what it should be, but I do feel I'm just trading one TODO for another here...

**Comment by jskeet** [comment]
Thanks for reporting this - not quite sure what's going on, but we'll check both the zone and type parts on Monday. Apologies for the frustration!

**Comment by sebbov** [comment]
Thanks Jon, not urgent on my end.

Also noting the versions used:

```
   <PackageReference Include="Google.Api.Gax.Grpc" version="2.2.1" />
   <PackageReference Include="Google.Cloud.Monitoring.V3" version="1.0.0" />
   <PackageReference Include="Google.Cloud.Logging.Log4Net" version="2.2.0" />
   <PackageReference Include="Google.Cloud.Logging.V2" version="2.1.0" />
```

Re the type:  I believe I noticed SD logging and some documentation to use `container`, not `gke_container`.  Perhaps this is being renamed from one to another (not sure what direction) and is causing this confusion.

**Comment by jskeet** [comment]
Darn - it looks like [monitoring](https://cloud.google.com/monitoring/api/resources) and [logging](https://cloud.google.com/logging/docs/api/v2/resource-list) have different names here.
I'll raise this internally.

**Comment by jskeet** [comment]
Just as an update, I *did* raise this internally, and I believe what we've got is the best we can do for now, but I'm hoping there'll be a better long-term fix eventually.

I'll leave this as a P2 bug.

**Comment by sebbov** [comment]
Besides the `gke_container` / `container` discrepancy, this issue also listed the `zone` label discrepancy.

Is the latter not something that could already get fixed?

I also notice that the values for both the `pod_id` and the `namespace_id` labels are unexpected to me:

The logs emitted for the (stderr of the) monitored resource by k8s (specifically fluentd, I suppose) themselves do populate the k8s pod name `my-app-789c7b6579-m2hh` in `pod_id` and the k8s namespace name (e.g. `staging`, `prod`, ...) in `namespace_id`;  whereas the `FromPlatform()` values contain UUIDs I cannot directly relate to my resources.

**Comment by sebbov** [comment]
Sure np.  The zone issue is a bit tied to the type, and the new ones tied to the zone one, but best to track these separately indeed.

**Comment by jskeet** [comment]
Reassigned to Amanda who is keeping track of this a lot better than I am... and indeed it may just be done already now. (I can't remember the details.)

**Comment by amanda-tarafa** [comment]
Unfortunately this is still as it was on January, different names for gke container resource in monitoring and logging. I will try and raise this again to see if there are plans for these names to converge.

**Comment by landrito** [comment]
@amanda-tarafa any updates?

**Comment by noahdietz** [comment]
Hi @amanda-tarafa any updates on this issue? Thanks!

**Comment by amanda-tarafa** [comment]
Hi @noahdietz no update yet, still different names for GKE container resource at the Logging and Monitoring APIs. I'm following internal issues on that and until that is not tackled there's not much we can do.

**Comment by jskeet** [comment]
This documentation may well be relevant, but I haven't worked out what it means in terms of what we need to do yet: https://cloud.google.com/monitoring/kubernetes-engine/migration

**Comment by jskeet** [comment]
Note to self: if we're able to access the GKE API from the host, the `monitoringService` and `loggingService` fields in [Cluster](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster) give us the info we need.

**Comment by JustinBeckwith** [comment]
@jskeet any issues assigning this over to you until Amanda is back?

**Comment by jskeet** [comment]
That's fine - I thought it already was :)

**Comment by jskeet** [comment]
Okay, there are two separate issues here, one simpler than the other:

- Logging now supports ingesting gke_container as well as container, so we can move to that; that's the scope of this original issue
- Migrating from Legacy Stackdriver to Stackdriver Kubernetes Engine Monitoring is tricker; I'll file a new issue for that.

**Comment by jskeet** [comment]
Created #347 for the migration part.
