### ISSUE TITLE
Unexpected value for the "gke container" monitored resource's zone label 

### ISSUE THREAD

**Issue by sebbov** [googleapis/gax-dotnet#264]
... populated by `MonitoredResourceBuilder.FromPlatform()`.

From my understanding this value should reflect the short (e.g. "us-...-d") form of the zone, not its longer / url form (`projects/.../zones/us-...-d`), which is currently the case (with `Google.Cloud.Logging.V2` 2.2.0).

See #233 for some more details.

**Comment by jskeet** [comment]
@amanda-tarafa could you look at this please?

**Comment by amanda-tarafa** [comment]
Will do.

**Comment by amanda-tarafa** [comment]
Closed via #269
