### ISSUE TITLE
Unexpected value for the "gke container" monitored resource's namespace_id and pod_id label

### ISSUE THREAD

**Issue by sebbov** [googleapis/gax-dotnet#265]
... populated by MonitoredResourceBuilder.FromPlatform().

The values for both the `pod_id` and the `namespace_id` labels are unexpected to me:

The logs emitted for the (stderr of the) monitored resource by k8s (specifically `fluentd`, I suppose) themselves do populate the k8s pod name (e.g., `my-app-789c7b6579-m2hh`) in pod_id and the k8s namespace name (e.g., `staging`) in namespace_id; whereas the `FromPlatform()` (with `Google.Cloud.Logging.V2` 2.2.0) values contain UUIDs I cannot directly relate to my resources.

This was forked off #233

**Comment by jskeet** [comment]
@amanda-tarafa could you look at this please?

**Comment by amanda-tarafa** [comment]
Will do.

**Comment by amanda-tarafa** [comment]
Closed via #269
