### ISSUE TITLE
The Application Default Credentials are not available

### ISSUE THREAD

**Issue by anveta** [googleapis/gax-dotnet#278]
I am facing some issue while setting an environment variable. Can anyone help me?

**Comment by jskeet** [comment]
I'm afraid we'll need a lot more detail about what you're trying and what's happening. Please could you provide more context? In particular:

- What operating system are you using?
- What kind of application are you running?
- How are you setting the environment variable?
- How are you running your application?
- Are you facing problems when developing, or when deploying to another machine (e.g. test or production)?

**Comment by anveta** [comment]
Actually I want to extract text from an image so, I am using Application Vision in C# windows form. 
In " var client = ImageAnnotatorClient.Create();"  this line i am facing issue.

Additional information: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by anveta** [comment]
This is my code : 

public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {


            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {

                string credentialPath = Environment.GetEnvironmentVariable("path");
                

                var client = ImageAnnotatorClient.Create();
                var image = Google.Cloud.Vision.V1.Image.FromFile(openFileDialog1.FileName);
                //var response = client.DetectLabels(image);
                var response = client.DetectText(image);
                textBox1.Text = "";

                foreach (var annotation in response)
                {
                    if (annotation.Description != null)
                    {
                        textBox1.Text += annotation.Description; //+ "\r\n"; 
                    }

                }

            }
        }
    }

**Comment by jskeet** [comment]
Okay, your code is fetching the `path` environment variable, but it's not clear why. The default application credentials are loaded from the `GOOGLE_APPLICATION_CREDENTIALS` environment variable - so if you set that environment variable on your machine to point at your credential file, that should work fine.

An alternative would be to load the credentials directly, without any environment variables - that's more code though, so I won't confuse the issue by explaining it just yet. Let me know if you want that information though.

**Comment by anveta** [comment]
Thanks for quick reply!
I am not able to enable API Vision. It is showing me error 

"An unhandled exception of type 'Grpc.Core.RpcException' occurred in mscorlib.dll

Additional information: Status(StatusCode=PermissionDenied, Detail="This API method requires billing to be enabled. Please enable billing on project #798984850744 by visiting " 
on line "var response = client.DetectText(image);". 

How can I fix this?

**Comment by jskeet** [comment]
As the error message says: you need to enable billing for your Cloud project. (I suspect that the error message also contains a link - but if it doesn't, https://console.cloud.google.com/billing should be what you need.

**Comment by jskeet** [comment]
Closing as I believe this is now addressed.
