### ISSUE TITLE
Error "The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials" using Google Speech to Text

### ISSUE THREAD

**Issue by NancyMH** [googleapis/gax-dotnet#316]
I been having problems with Credentials using Google Cloud Speech to Text API. 
I am creating an application with Netbeans and when I run it I get the error:

> Exception in thread "main" java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

If I run the Application in Google Cloud SDK Shell everything works well because I manually set the credentials with the command: "set GOOGLE_APPLICATION_CREDENTIALS=C:\Users\Nancy\Desktop\Gasolineras\ProyectoPrueba1\My First Project-ed7b9af22cbd.json"

But If I run it in Netbeans it does not work.

Here is my code:

    // Imports the Google Cloud client library
    import com.google.auth.oauth2.GoogleCredentials;
    import com.google.cloud.speech.v1.RecognitionAudio;
    import com.google.cloud.speech.v1.RecognitionConfig;
    import com.google.cloud.speech.v1.RecognitionConfig.AudioEncoding;
    import com.google.cloud.speech.v1.RecognizeResponse;
    import com.google.cloud.speech.v1.SpeechClient;
    import com.google.cloud.speech.v1.SpeechRecognitionAlternative;
    import com.google.cloud.speech.v1.SpeechRecognitionResult;
    import com.google.protobuf.ByteString;
    import java.io.FileInputStream;
    import java.io.IOException;
    import java.nio.file.Files;
    import java.nio.file.Path;
    import java.nio.file.Paths;
    import java.util.List;
    import com.google.api.gax.paging.Page;
    import com.google.cloud.storage.Bucket;
    import com.google.cloud.storage.BucketInfo;
    import com.google.cloud.storage.Storage;
    import com.google.cloud.storage.StorageOptions;
    import com.google.common.collect.Lists;

    public class QuickstartSample {

        static void authExplicit(String jsonPath) throws IOException {
       // You can specify a credential file by providing a path to GoogleCredentials.
      // Otherwise credentials are read from the GOOGLE_APPLICATION_CREDENTIALS environment variable.
      GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream(jsonPath))
        .createScoped(Lists.newArrayList("https://www.googleapis.com/auth/cloud-platform"));
      Storage storage = StorageOptions.newBuilder().setCredentials(credentials).build().getService();
      System.out.println("Buckets:");
      Page<Bucket> buckets = storage.list();

      for (Bucket bucket : buckets.iterateAll()) {
        System.out.println(bucket.toString());
      }
    }

     // Demonstrates using the Speech API to transcribe an audio file
      QuickstartSample.authExplicit("C:\\Users\\Nancy\\Desktop\\Gasolineras\\ProyectoPrueba1\\My First Project-ed7b9af22cbd.json"); 
    
    
    // Instantiates a client
    try (SpeechClient speechClient = SpeechClient.create()) {

      // The path to the audio file to transcribe
      String fileName = "C:\\Users\\Nancy\\Desktop\\Gasolineras\\Audios de prueba\\otros\\Gracias.wav";

      // Reads the audio file into memory
      Path path = Paths.get(fileName);
      byte[] data = Files.readAllBytes(path);
      ByteString audioBytes = ByteString.copyFrom(data);

      // Builds the sync recognize request
      RecognitionConfig config = RecognitionConfig.newBuilder()
          .setEncoding(AudioEncoding.LINEAR16)
          //.setSampleRateHertz(16000)
          .setLanguageCode("es-MX")
          .build();
      RecognitionAudio audio = RecognitionAudio.newBuilder()
          .setContent(audioBytes)
          .build();

      // Performs speech recognition on the audio file
      RecognizeResponse response = speechClient.recognize(config, audio);
      List<SpeechRecognitionResult> results = response.getResultsList();

      for (SpeechRecognitionResult result : results) {
        // There can be several alternative transcripts for a given chunk of speech. Just use the
        // first (most likely) one here.
        SpeechRecognitionAlternative alternative = result.getAlternativesList().get(0);
        System.out.printf("Transcription: %s%n", alternative.getTranscript());
       }
     }
    }
    }

As you can see, in the code I also put the path to my .json file that contains the necessary credentials, but I still get the error.
Hope someone can help me, I'm tired to search at web and dont find anything useful.

**Comment by jskeet** [comment]
I think you've posted in the wrong repository - I suggest you post this in https://github.com/googleapis/google-cloud-java... But in terms of the environment variable, you either need to set it in the overall environment instead of just your shell, or set it in your Netbeans configuration.

If you press the Windows key and type "environment" you should get an option to set either user or system environment variables. If suggest setting this as a user environment variable. Then restart Netbeans, and it should pick it up.

**Comment by NancyMH** [comment]
Thanks for answer @jskeet I will post it in the other repository. I should set this environment variable as a user environment variable in Path or I should create a new user variable?

**Comment by jskeet** [comment]
It's a new environment variable - the name is GOOGLE_APPLICATION_CREDENTIALS; it's not part of the PATH environment variable.

**Comment by NancyMH** [comment]
It works!! Thank you so much @jskeet

**Comment by moander** [comment]
Just for the reference. I started seeing the same error after upgrading to `Google.Cloud.Storage.V1` v3.0.0. The app is hosted in Cloud Run (managed). Base image `mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine`.

The weird thing is that it happens sporadically.

**Comment by jskeet** [comment]
@moander: This was originally an issue about Java. Please file a new issue, ideally in https://github.com/googleapis/google-cloud-dotnet with precise details.
