### ISSUE TITLE
ScopedCredentialProvider.GetCredentials and GoogleCredential.GetApplicationDefaultAsync

### ISSUE THREAD

**Issue by john-larson** [googleapis/gax-dotnet#323]
I am trying to retrieve access token for the translation service. There does not seem to be a clear documentation on how to accomplish this but I have found the following two methods:

    private static ScopedCredentialProvider ScopedCredentialProvider { get; } =
        new ScopedCredentialProvider(new[] { TranslateService.Scope.CloudPlatform });
    var scopedCredentials = ScopedCredentialProvider.GetCredentials(null);
    string accessToken = await scopedCredentials.UnderlyingCredential.GetAccessTokenForRequestAsync();

and 

    var googleCredential = (ServiceAccountCredential)GoogleCredential.GetApplicationDefaultAsync().Result.CreateScoped(TranslateService.Scope.CloudTranslation).UnderlyingCredential;
    string accessToken = await googleCredential.GetAccessTokenForRequestAsync();

My requirements are:
1. Token should be cached until expired. So I should not be getting a new token at every request.
2. Token should be automatically refreshed when expired.

Using `GoogleCredential.GetApplicationDefaultAsync` causes a request to the oauth endpoint of google and generates a new token every single time. But `ScopedCredentialProvider` seems to be caching the token, preventing an extra request. I haven't yet tested if it will refresh the token when expired though. Is the expiration window 60 minutes?

So, given my requirements, is `ScopedCredentialProvider` the right api to use? The comment on https://github.com/googleapis/google-api-dotnet-client/issues/1242#issuecomment-398817770 indicates that  `GoogleCredential.GetApplicationDefaultAsync` should also act this way but it does not seem to. Is it because I am using it wrong?

**Comment by jskeet** [comment]
`ScopedCredentialProvider` is particularly designed for the use cases we have in the client libraries - in particular, using a single set of "application default credentials with given scopes" even when multiple clients are involved. Without knowing *exactly* what you're trying to do, it's hard to know whether it meets your needs, but usually I'd expect just `GoogleCredential` to be what you want.

If you can give more information about why you want the access token rather than just using the client libraries to make the requests, I may be able to help you more. (I'm on vacation tomorrow though, so replies may be a bit delayed.)

**Comment by john-larson** [comment]
@jskeet I am trying to use Translate v3beta APIs. As far as I understand, current C# client for translation does not support v3beta yet. So I thought I could just use the REST APIs through C#. But that requires an access token to be generated. So after giving ScopedCredentialProvider and GoogleCredential a try, it seems like ScopedCredentialProvider meets my needs of caching and refreshing the token. 

As you mentioned, I'd prefer using GoogleCredential since ScopedCredentialProvider seems to be geared towards the client libraries. But it makes a request to oauth2.googleapis.com and creates a new token each time. So there seems to be no caching. But googleapis/google-api-dotnet-client#1242 (comment)  claims that there is. So I just wondered if I am doing something wrong when using it.

**Comment by jskeet** [comment]
Are you creating a new TranslateService for each request? If you are, can you avoid doing so? That would be the simplest approach - that would use a single scoped GoogleCredential, which would cache the token.

**Comment by john-larson** [comment]
Just to be on the same page, I am not using the Translate client library, so I am not creating any TranslateService instances. I am simply creating GET and POST http requests. And the only thing I need is the access token that I need to pass to these http requests.

**Comment by jskeet** [comment]
Ah, right - apologies, I thought there was a NuGet package for the v3beta, just not with the manually-written simplification.

But basically, if you reuse a single `GoogleCredential` to get the access token every time, I believe it should do the caching for you. If you could provide a sample program we could both work on, that would make it easier to be concrete about this.

**Comment by john-larson** [comment]
You are right, I was creating a new instance every time and that was the problem. Thanks.

**Comment by jskeet** [comment]
Great! Will close the issue now as it sounds like you're all set.
