### ISSUE TITLE
Missing CONTRIBUTING.md leading to 404 page

### ISSUE THREAD

**Issue by kshithijiyer** [googleapis/gax-dotnet#331]
#### Environment details

  - OS: NA
  - .NET version: NA
  - `gax` version: NA

#### Steps to reproduce

  1. Click on CONTRIBUTING hyperlink on README.md file
  2. 404 page appears 

Code causing issue:
```
See the
[CONTRIBUTING](https://github.com/googleapis/gax-dotnet/blob/master/CONTRIBUTING)
documentation for more information on how to get **started.**

```

**Comment by jskeet** [comment]
Thanks - for the moment I'll just remove this from the readme. (We do welcome contributions, but we don't particularly expect them for this project - it's more internal support for other client libraries.)
