### ISSUE TITLE
Support System.Interactive.Async 4.0.0 

### ISSUE THREAD

**Issue by tangkhaiphuong** [googleapis/gax-dotnet#376]
I use with ASP.NET Core 3.1 and got this issue.

`Detected package version outside of dependency constraint: Google.Api.Gax 2.10.0 requires System.Interactive.Async (>= 3.2.0 && < 4.0.0) but version System.Interactive.Async 4.0.0 was resolved.`

**Comment by jskeet** [comment]
Yes, Google.Api.Gax v2.x does not support System.Interactive.Async 4.0, and won't.

Google.Api.Gax v3.0 *will* support System.Interactive.Async 4.0. We're currently working hard on making updating all the libraries in [the google-cloud-dotnet repo](https://github.com/googleapis/google-cloud-dotnet) to use Google.Api.Gax v3.0; once that's all ready, we'll start releasing alphas, then betas, then go to GA. See https://googleapis.github.io/google-cloud-dotnet/docs/major-version.html for the reasons for all of this, and the plan.

**Comment by jskeet** [comment]
I'm going to close this issue as we already have https://github.com/googleapis/google-cloud-dotnet/issues/3519 which is *effectively* the same, but from a different perspective. (Or at least, they'll both be fixed by the same changes.) I suggest you subscribe to that issue to follow along.
