### ISSUE TITLE
Consider removing ServiceEndpoint in 2.x

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#379]
It's somewhat late in the day to do this, but I want to at least investigate the idea of removing ServiceEndpoint.

This is motivated by #357, and the [gRPC documentation](https://grpc.github.io/grpc/cpp/md_doc_naming.html). We really don't want to have to mimic all the different available schemes in gRPC, within ServiceEndpoint - we'd always be playing catchup.

For now, I'll document what would be required to remove ServiceEndpoint, then we can consider it in more detail.

**Comment by jskeet** [comment]
cc @jtattermusch

**Comment by jtattermusch** [comment]
FTR, only somewhat related https://github.com/grpc/grpc/issues/20375

**Comment by jtattermusch** [comment]
IMHO passing strings as endpoints is fair and also consistent with how C-core handles channel targets.
