### ISSUE TITLE
Separate "API proto types" from GAX?

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#39]
Currently we include the generated code for google.api.* etc in Google.Gax.
We should consider putting it in a separate package instead. More dependencies, admittedly... but it would make for more sensible versioning.

**Comment by jskeet** [comment]
There's a good reason to do this that I hadn't considered before - it makes it simpler for 3rd parties to work with just the protobuf types. For example, there's been a feature request / offer of work for a Noda Time to protobuf serialization package, which would want to depend on these protobuf types but not on anything in Gax.

@chrisdunelm: This will affect the dependencies in gcloud-dotnet, but we probably _won't_ need a dependency within `Google.Api.Gax`. I think it's reasonable for both packages to have their source code in their repo. Are you happy for me to just get on with this?

**Comment by chrisdunelm** [comment]
@jskeet I agree this is a good idea. Yes, feel free to just do it.
