### ISSUE TITLE
Potentially unnecessary redirect in Platform.LoadMetadataAsync

### ISSUE THREAD

**Issue by shaneqld** [googleapis/gax-dotnet#410]
Hi,

I hope you are all well.  I can see effort has been made to optimize the Platform class, so I am reporting this small potential optimization.

The metadata URL is determined by:

```cs
var metadataUrl = $"http://{effectiveMetadataHost}/computeMetadata/v1?recursive=true";
```

Following from that, within a container running in GKE, I ran:

```
curl http://169.254.169.254/computeMetadata/v1?recursive=true -H "Metadata-Flavor: Google" -v
```

And it returned a 301 Redirect to http://169.254.169.254/computeMetadata/v1/?recursive=true

i.e. it's expecting a trailing slash on the path.

Assuming this is how the metadata servers handle this universally, I suggest adding a trailing slash on the path in the code, to avoid the 301.

**Comment by jskeet** [comment]
Thank you for raising this - we'll need to check whether it *is* valid everywhere, but it does sound like it would be a good thing to do.
(We're unlikely to get to it *very* soon due to other work we have on at the moment, but we won't forget about it.)
