### ISSUE TITLE
Determine container name with no access to kube-apiserver

### ISSUE THREAD

**Issue by shaneqld** [googleapis/gax-dotnet#411]
Initially posted in #305.

When first working with this package, the library was not determining the containerName in my GKE environment. This was caused by my Istio mTLS policy preventing access to kube-apiserver, in addition to my k8s service account not have enough permissions.

I note the code that retrieves the containerName runs this Regex over the contents of /proc/self/mountinfo:

```cs
var regex = new Regex($"/var/lib/kubelet/pods/{podUid}/containers/([^/]+)/.*/dev/termination-log");
```

In my case, this had no matches, as `podUid` could not be determined from kube-apiserver.

One cat and grep later (within a gke container), I noted that there was only one possible match for this regex in /proc/self/mountinto (when substituting `{podUid}` with `[^/]+`).

As pods and containers have their own file system, might it be suitable to disregard the podUid when determining the containerName (even as a fallback)? This should allow the determination of containerName even with no kube-apiserver access.

Cheers,
Shane.

**Comment by jskeet** [comment]
Thanks! Will look into this when I get a chance, which is likely to be next week.

**Comment by jskeet** [comment]
Okay, one year later... yes, that does seem fairly reasonable. I think we should probably be looking for a space before /dev/termination-log as well. Will see what I can do.
