### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gax-dotnet#416]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by chrisdunelm** [comment]
Jon , can you take a look at this - I don't think I'm an admin on this repo, so can't make these changes.

**Comment by jskeet** [comment]
Done - I don't think we have any special requirements here. (I still need to work out what to do with google-api-dotnet-client.)
