### ISSUE TITLE
Move extension methods to different namespace to not cause conflicts

### ISSUE THREAD

**Issue by nycdotnet** [googleapis/gax-dotnet#418]
**Is your feature request related to a problem? Please describe.**

In the Google.Api.CommonProtos assembly v2.0 and v2.1, there is a new type called `Google.Type.DateTime`.  We generally don't use this in our protos, but we do use `Google.Type.Date`.  There are helpful extension methods for use with `Google.Type.Date` that convert them to and from `System.DateTime`.  The trouble is that the extension methods live in the `Google.Type` namespace.  This means that to access these extension methods, you must have `using Google.Type;` in your file which, assuming `using System;` is also present, causes there to be a conflict between `System.DateTime` and `Google.Type.DateTime`.

`Error	CS0104	'DateTime' is an ambiguous reference between 'Google.Type.DateTime' and 'System.DateTime'`

Here is a console app demonstrating this which uses only the Google.Api.CommonProtos 2.1 NuGet package.  The below program builds successfully using Google.Api.CommonProtos version 1.7 (which does not have `Google.Type.DateTime`).

```csharp
using System;
using Google.Type;

class Program
{
    static void Main(string[] _)
    {
        var desiredSystemDateTime = new DateTime(2020, 1, 1);
        var desiredGoogleTypeDate = desiredSystemDateTime.ToDate();
    }
}
```

 **Describe the solution you'd like**

I would like the extension methods to be moved to a new `Google.Type.Extensions` namespace.  This would allow us to import and use the built-in conversion extension methods (which we love), and through judicious use of `var`, generally not have to import `Google.Type`.  This would also let us not have to go through all of our code bases and figure out which `DateTime` we meant in every file as we upgrade to newer versions of Google.Api.CommonProtos.

 **Describe alternatives you've considered**
In theory we could wrap the extensions we want in our own namespace and import that, or else just qualify `System.DateTime` everywhere, but this seems like a lot of work.  I guess we could also do `DateTime = System.Datetime`, but again I'd prefer to just change the namespace for the extensions as this seems less likely to have breakage long-term.

 **Additional context**

This is totally our fault as a Namely engineer was the person who contributed the `Google.Type.Date` extensions in the first place.  https://github.com/googleapis/gax-dotnet/pull/251/files  At that time, though, there were no types that conflicted with the name of a type in the `System` namespace, however, so this wasn't conceived of as an issue.  Thanks for all of your hard work on this library.  I am willing to make a PR to move the extension methods to a `Google.Type.Extensions` namespace if that is of interest to you as a solution.

**Comment by jskeet** [comment]
No, we can't move the extension methods - that would be a breaking change, and creating a major version bump for this library would require a major version bump for *dozens* of others too - which I really don't think it justified here.

Fortunately there's a really simple way of avoiding it being a problem: use `using static` instead to import the class containing the extension methods you want:

```csharp
using System;
using static Google.Type.DateExtensions;

class Program
{
    static void Main(string[] _)
    {
        var desiredSystemDateTime = new DateTime(2020, 1, 1);
        var desiredGoogleTypeDate = desiredSystemDateTime.ToDate();
    }
}
```

**Comment by nycdotnet** [comment]
Ah - well done.  We will proceed with that.  Thank you.
