### ISSUE TITLE
Fix typo in Nuget Project URL for older package versions

### ISSUE THREAD

**Issue by robert-mccausland** [googleapis/gax-dotnet#469]
Hi,

We are currently have an issue resolving certain Nuget packages and we have tracked it down to our Nuget server failing to parse the metadata files for packages due to the `projectUrl` not being a valid URL. It looks like this was fixed a while ago in [this commit](https://github.com/googleapis/gax-dotnet/commit/38f205185326f9fa177028e77b23fe7013df2bc5), however the old versions of the nuget package still have the old incorrect `projectUrl`, and this is causing us issues when trying to resolve newer versions of the package.

To be clear, this is really a bug with our Nuget server's implementation, our Nuget server is configured to use nuget.org as an upstream source, and our Nuget server fails to resolve the packages because it can't handle the `projectUrl` not being a valid URL. but there is nothing fundamentally wrong with the packages. However this is a blocking issue at the moment so I am trying to cover all our bases.

For example, getting metadata for "Google.Api.Gax" from this endpoint: https://api.nuget.org/v3/registration5-semver1/google.api.gax/index.json, will contain the wrong `projectUrl`, but only for the older versions of the package (it was fixed in 1.0.0-beta07). Would it be possible to update the metadata of the old packages versions to have the correct `projectUrl`?

**Comment by jskeet** [comment]
As far as I'm aware, it's impossible to update anything about a package after it's published. The only option is delisting it. I'm happy to delist pre-1.0.0 versions of Google.Api.Gax, but only if you can confirm that would actually solve the problem. (It probably depends on how you're fetching the metadata.)

**Comment by jskeet** [comment]
(Any chance you could just perform a filter for "not fetching package versions older than 2017" instead?)

**Comment by robert-mccausland** [comment]
I don't think we can filter package versions, as I think we are grabbing the metadata from the "https://api.nuget.org/v3/registration5-semver1/{id-lower}/index.json" endpoint. If delisting pre-1.0.0 versions will remove them from that endpoint that it should fix our problem.

**Comment by jskeet** [comment]
I honestly don't know whether it will fix the problem - and you're talking about delisting 30 packages, which is not an insignificant amount of work. Are you able to test this yourself by delisting one of your own packages temporarily?

**Comment by jskeet** [comment]
Actually, I'll see if I can find something I've delisted in the past... we should be able to test that way. (But the sooner you can get your NuGet server fixed, the better... this isn't really work that should be propagated to third party package owners for a mistake fixed 5 years ago...)

**Comment by jskeet** [comment]
It looks like that URL still includes delisted packages. See https://api.nuget.org/v3/registration5-semver1/google.apis.clouddatabasemigrationservice.v1beta1/index.json for example - there are [no listed versions for that package](https://www.nuget.org/packages/Google.Apis.CloudDatabaseMigrationService.v1beta1/) but they're still showing up in that URL. I don't think there's anything I can do to help you here, I'm afraid.

**Comment by robert-mccausland** [comment]
Yea, I just checked myself and came to the same conclusion.

Apologies for bothering you with this - I was hoping there would be a way of updating the metadata on the old packages, but it looks like there is no way of doing it.

**Comment by jskeet** [comment]
Best of luck finding a workaround or implementing a fix. I'll close this issue now.
