### ISSUE TITLE
Consider the GrpcAdapter.Default API

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#529]
Should clients be able to set it manually? Clear the default?

**Comment by amanda-tarafa** [comment]
I was also thinking more in terms of DI. But I think the entry point for that would be more on `ClientBuilderBase` and its implementations (which would benefit REGAPIC as well). Something like:

- Change `GrpcAdapter.Default` -> `GrpcAdapter.Fallback`, and keep the current heuristic of trying to create a channel + possibly and env variable to determine whether it's Grpc.Core or Grpc.Net.Client.

And o one of the following options:

1. At a minimum add a constructor to ClientBuilderBase that takes a GrpcAdapter, so the builder can be itself registered for DI, with an injected Adapter. If null, use `GrpcAdapter.Fallback`.
2. Or add static factory methods to the generated ClientBuilders (a little weird to have a factory for a builder) that take the Adapter and any other 
3. Or possibly the better option is to add DI extension methods for registering the builder and maybe even the client directly (even if we internally use the builder). This of course means that we need a dependency on MS's DI, which we might not want.
4. Do 3. but in a separate powerpack like library, generic on ClientBuilderBase and ClientBase, where we can take the DI dependency easily.
5. Do nothing in production code but write examples for approaches 2. (the factory methods to be outside of the classe) and 3.

I like 4, the best, what do you think?

**Comment by jskeet** [comment]
Not sure yet... but I'll think about it. I suspect we should probably write a mini-PRD for this, so that we really know what we're trying to achieve...

**Comment by jskeet** [comment]
Not sure yet... but I'll think about it. I suspect we should probably write a mini-PRD for this, so that we really know what we're trying to achieve...

**Comment by jskeet** [comment]
We've now overhauled this a *lot*, and I think we're happy with it.
