### ISSUE TITLE
Google.Api.Gax.Grpc.GrpcCore package reports being compatible with Google.Api.Gax.Grpc 4, but is not

### ISSUE THREAD

**Issue by billybraga** [googleapis/gax-dotnet#578]
As I understand it, Google.Api.Gax.Grpc.GrpcCore (latest, 3.7.0) is not meant to be used with gax 4, but the nuget package says it requires Google.Api.Gax.Grpc >= 3.7.0 (meaning it's compatible with Google.Api.Gax.Grpc 4.0, gax 4). This causes conflicts, for example, when using the most recent non-beta librairies of PubSub and Firestore, because Google.Cloud.PubSub.V1 (latest, 2.10.0) uses Google.Api.Gax.Grpc.GrpcCore (Google.Cloud.PubSub.V1 3.0, the one using gax 4, is in beta).

#### Environment details

  - OS: 
  - .NET version:
  - `gax` version: 4

#### Steps to reproduce

  1. Install Google.Cloud.Firestore (latest, 3.0.0)
  2. Install Google.Cloud.PubSub.V1 (latest, 2.10.0)
  3. Try to instantiate a PublisherServiceApiClientBuilder
  4. Gives `System.MissingMethodException : Method not found: 'Void Google.Api.Gax.Grpc.ClientBuilderBase`1..ctor()'.`

**Comment by jskeet** [comment]
The latest version of Google.Cloud.PubSub.V1 isn't 2.10.0 - it's 3.0.0-beta01, and *that* depends on GAX v4.

The only we haven't released Google.Cloud.PubSub.V1 version 3.0.0 is that there's a new feature under development which *might* require an API breaking change. (It's unlikely, but it would be very frustrating to go GA with 3.0.0 and then need a 4.0.0 almost immediately.)

I suggest you update to use 3.0.0-beta01 - even though it's technically a pre-release, that's only in terms of API surface stability... the actual code is fine to rely on. (It's basically 2.10.0 with the changes required to use GAX v4.)

**Comment by billybraga** [comment]
Ok, thanks

**Comment by jskeet** [comment]
We've now released 3.0.0, so you should be able to update to that. (There are no changes since the beta - but it's obviously cleaner to have GA releases available.)
