### ISSUE TITLE
Grpc duplicates request headers when using Grpc.Net.Client, but not when using Grpc.Core

### ISSUE THREAD

**Issue by AnashOommen** [googleapis/gax-dotnet#672]
#### Environment details

  - OS: Windows
  - .NET version: 5.0
  - `gax` version: 4.3.0

#### Steps to reproduce

Consider the following code, which is a simplified code from the Google Ads API library (this detail is hidden to the user, but replicated here to explain the problem).  We are creating a campaign budget.

```
// Create the campaign budget.
CampaignBudget budget = new CampaignBudget()
{
  Name = "Interplanetary Cruise Budget #" + ExampleUtilities.GetRandomString(),
  DeliveryMethod = BudgetDeliveryMethod.Standard,
  AmountMicros = 500000
};

// Create the operation.
MutateOperation operation = new MutateOperation()
{
  CampaignBudgetOperation = new CampaignBudgetOperation()
  {
    Create = budget
  }
};

MutateGoogleAdsRequest request = new MutateGoogleAdsRequest()
{
  CustomerId = "9185018835",
  MutateOperations = { operation },
  PartialFailure = true
};

var channelCredentials = GoogleGrpcCredentials.ToChannelCredentials(config.Credentials);
Uri uri = new Uri("https://googleads.googleapis.com");

GrpcChannelOptions options = new GrpcChannelOptions();
options.Credentials = channelCredentials;

// Commented code, uncomment the correct version when using Grpc.Core v/s Grpc.Net.Client.
//ChannelBase channel = GrpcChannel.ForAddress(uri, options);
ChannelBase channel = new Channel(uri.Host, uri.Port, channelCredentials);

CallInvoker invoker = channel.CreateCallInvoker();

GoogleAdsServiceSettings settings = new GoogleAdsServiceSettings();
CallSettings callSettings = settings.MutateSettings;
callSettings = callSettings.WithHeader("login-customer-id", config.LoginCustomerId);
callSettings = callSettings.WithHeader("developer-token", config.DeveloperToken);
settings.MutateSettings = callSettings;

// Notice how we are using the same callsettings when creating the service AND when making the calls.
var newService = GoogleAdsServiceClient.Create(invoker, settings);
var results = newService.Mutate(request, callSettings);
```

If you uncomment the Grpc.Core version, the call succeeds. If you uncomment the Grpc.Net.Client version instead, then the server fails the call with an error like this:

```
Fault: {
  "StatusCode": 3,
  "Details": "Request contains an invalid argument.",
  "RequestId": "K0m_VlCytOma7GUP1pKfYw",
  "Failure": {
    "errors": [
      {
        "errorCode": {
          "headerError": "INVALID_LOGIN_CUSTOMER_ID"
        },
        "message": "The login customer id header 'Optional[7605500390, 7605500390]' could not be validated."
      }
    ],
    "requestId": "K0m_VlCytOma7GUP1pKfYw"
  }
}
```

See how the error message suggests that the login-customer-id header is duplicated by the library when using Grpc.Net.Client. 

I don't know if this is a bug with the generated code, Grpc.Core code or the specific CallInvoker implementation. But it definitely looks like we are missing a CallSettings.Merge call somewhere.

**Comment by jskeet** [comment]
I suspect this is due to a difference we've seen in other circumstances, where Grpc.Core uses separate headers for repeated ones and Grpc.Net.Client comma-separates them instead. I suspect the server *should* fail with the Grpc.Core version as well, but that it's just ignoring the repeated header.

@amanda-tarafa knows more about this, after diving into this for a routing issue.

Fundamentally, that code *is* specifying the header twice, by using the same CallSettings more than once. The two CallSettings objects are each applied, and they both add the header.

**Comment by AnashOommen** [comment]
I thought that the whole point of supporting Callsettings at service, method and call levels was that they will all be merged, and the developers no longer have to worry about how and where they set configs, and that they can override things at service level at the call level. Did I misunderstand things?

I think the developer is cloning the CallSettings here because there's no good way to create an empty CallSetting as far as I know. Perhaps we can have a 

```
var callsettings = CallSettings.Empty;
// Set more settings here.
var results = newService.Mutate(request, callsettings );
```

**Comment by AnashOommen** [comment]
I think it is more like "we provided an interface, they used it with weird
consequences". I showed them an example of what they wanted to do
(cancellation token for individual calls, headers from service level), but
they didn't know how to make a call setting, so they took an existing one
and added a with... to get a new call setting.

Perhaps what we need is some documentation about how call settings are
merged, except for header.

**Comment by jskeet** [comment]
It's not a matter of "call settings are merged, except for header" - it's a matter of "call settings are merged, including header additions". If you've got two CallSettings each of which adds a header, then the merged CallSettings adds both headers *even if they're for the same name*. (The docs for `CallSettings.ForHeader` talk in terms of "the name of the header to add" for example.)

We can definitely make that clearer in the docs though, I agree.

**Comment by AnashOommen** [comment]
It would be helpful to share the docs link once you update it. I can then update our libary's FAQ section.

**Comment by jskeet** [comment]
(Added type/assignment to avoid this being regarded as untriaged.)
