### ISSUE TITLE
Add proto files to `Google.Api.CommonProtos`

### ISSUE THREAD

**Issue by mrt181** [googleapis/gax-dotnet#715]
I'm always frustrated when I have to use C# with Protobuf to generate code from proto definitions.

The package `Google.Protobuf.Tools` contains the proto definitions for well known types.

These can be used in my own proto definitions.
```xml
<PackageReference Include="Google.Protobuf.Tools" Version="3.24.2" GeneratePathProperty="true"/>

<Protobuf AdditionalImportDirs="$(PkgGoogle_Protobuf_Tools)\tools" />
```

But the `Google.Api.CommonProtos` package does not contain its proto definitions.

Whenever someone needs to use some definition from here:
[googleapis/googleapis](https://github.com/googleapis/googleapis/tree/master/google/)

these files need to be provided manually somehow.

For java there exists a package that contains those protos
[com.google.api.grpc:proto-google-common-protos](https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos)
and which are picked up by the different build tool plugins for proto code generation.

Can you add the proto definitions for googleapis to the `Google.Api.CommonProtos` package?

**Comment by jskeet** [comment]
Thanks for the suggestion - we'll discuss it internally.

**Comment by mrt181** [comment]
`Grpc.Tools` also contains the well known types and adds them automatically to the protoc command.
```shell
/home/martin/.nuget/packages/grpc.tools/2.57.0/tools/linux_x64/protoc --csharp_out=obj/Debug/net7.0/exchange/v1 --plugin=protoc-gen-grpc=/home/martin/.nuget/packages/grpc.tools/2.57.0/tools/linux_x64/grpc_csharp_plugin --grpc_out=obj/Debug/net7.0/exchange/v1 --grpc_opt=no_server --proto_path=/home/martin/repos/dotnet-test/ConsoleApp1 --proto_path=/home/martin/.nuget/packages/uci.proto.model/1.0.1/content/src/main/proto --proto_path=/home/martin/.nuget/packages/grpc.tools/2.57.0/build/native/include --proto_path=/home/martin/.nuget/packages/my.proto.model/1.0.1/content/src/main/proto --dependency_out=obj/Debug/net7.0/4ba3b8cb2bc5994c_params.protodep --error_format=msvs /home/martin/.nuget/packages/my.proto.model/1.0.1/content/src/main/proto/my/v1/params.proto
```

this is the path that is added
```
--proto_path=/home/martin/.nuget/packages/grpc.tools/2.57.0/build/native/include
```

This should also happen for the proto files from googleapis/googleapis.

**Comment by jskeet** [comment]
Just coming back to this now... is there still value here if we *don't* add anything to the path automatically? I'm slightly nervous of this as we don't use any of the msbuild tools ourselves for protoc - we just invoke it directly. That makes it more likely that I could break things without knowing.

It would be easy enough to add targets [like these](https://github.com/dotnet/aspnetcore/blob/main/src/Grpc/JsonTranscoding/src/Microsoft.AspNetCore.Grpc.JsonTranscoding/build/Microsoft.AspNetCore.Grpc.JsonTranscoding.targets) but with different property names... but I'd rather take things one step at a time.

**Comment by jskeet** [comment]
Scratch the "one step at a time" - given the (unmerged, but reasonable) [documentation](https://github.com/grpc/grpc/pull/34521) for doing this consistently, I'm happy to have the msbuild magic as well.

I've just tried it, and it worked seamlessly.
